<?php
/**
 * TL_ROOT/system/modules/boxes/languages/nl/tl_boxen.php 
 * 
 * TYPOlight extension: boxes 1.10.2 stable 
 * Dutch translation file 
 * 
 * Copyright : &copy; 2007 Christian Wenzel / &copy; 2008 computino.de Webservice 
 * License   : GPL v2 
 * Author    : Markus Milkereit (markus.milkereit), http://www.computino.de 
 * Translator: Just Schimmelpenninck (justs) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_boxen']['title']['0'] = "Titel";
$GLOBALS['TL_LANG']['tl_boxen']['title']['1'] = "Titel";
$GLOBALS['TL_LANG']['tl_boxen']['headline']['0'] = "Kopregel";
$GLOBALS['TL_LANG']['tl_boxen']['headline']['1'] = "De kopregel wordt - indien gewenst - getoond boven het element.";
$GLOBALS['TL_LANG']['tl_boxen']['content']['0'] = "Inhoud";
$GLOBALS['TL_LANG']['tl_boxen']['cssID']['0'] = "Style sheet ID en class";
$GLOBALS['TL_LANG']['tl_boxen']['cssID']['1'] = "Geef hier een style sheet ID (id attribute) en een of meerdere style sheet classes (class attributes) om het element vorm te geven.";
$GLOBALS['TL_LANG']['tl_boxen']['pages']['0'] = "Pagina's";
$GLOBALS['TL_LANG']['tl_boxen']['pages']['1'] = "Selecteer een of meerdere pagina's waarin de box getoond moet worden.";
$GLOBALS['TL_LANG']['tl_boxen']['position']['0'] = "Positie / volgorde";
$GLOBALS['TL_LANG']['tl_boxen']['position']['1'] = "Geef een volgnummer om de volgorde van de boxen te bepalen.";
$GLOBALS['TL_LANG']['tl_boxen']['modul_id']['0'] = "Verbind met module";
$GLOBALS['TL_LANG']['tl_boxen']['modul_id']['1'] = "Kies de box-module waarin de box getoond moet worden. Lees de handleiding voor meer informatie.";
$GLOBALS['TL_LANG']['tl_boxen']['space']['0'] = "Ruimte voor en achter";
$GLOBALS['TL_LANG']['tl_boxen']['space']['1'] = "Geef de ruimte in pixels voor en achter het inhoudselement op.";
$GLOBALS['TL_LANG']['tl_boxen']['addImage']['0'] = "Afbeelding toevoegen";
$GLOBALS['TL_LANG']['tl_boxen']['addImage']['1'] = "Als u deze optie selecteert kan u een afbeelding aan het artikel toevoegen.";
$GLOBALS['TL_LANG']['tl_boxen']['imageUrl']['0'] = "Gebruik afbeelding als link";
$GLOBALS['TL_LANG']['tl_boxen']['imageUrl']['1'] = "Geef een complete URL op (bv. http://www.domein.com) om een afbeelding als link te gebruiken. Bemerk dat het in dit geval niet meer mogelijk zal zijn om de afbeelding op ware grootte te zien.";
$GLOBALS['TL_LANG']['tl_boxen']['title_legend'] = "Titel en kopregel";
$GLOBALS['TL_LANG']['tl_boxen']['text_legend'] = "Tekst inhoud";
$GLOBALS['TL_LANG']['tl_boxen']['image_legend'] = "Afbeelding instellingen";
$GLOBALS['TL_LANG']['tl_boxen']['column_legend'] = "Module instellingen";
$GLOBALS['TL_LANG']['tl_boxen']['protected_legend'] = "Bescherm element";
$GLOBALS['TL_LANG']['tl_boxen']['pages_legend'] = "Pagina-afhankelijke weergave";
$GLOBALS['TL_LANG']['tl_boxen']['expert_legend'] = "Extra instellingen";
$GLOBALS['TL_LANG']['tl_boxen']['new']['0'] = "Maak een nieuwe box";
$GLOBALS['TL_LANG']['tl_boxen']['edit']['0'] = "Verander";
$GLOBALS['TL_LANG']['tl_boxen']['copy']['0'] = "Kopieer";
$GLOBALS['TL_LANG']['tl_boxen']['delete']['0'] = "Wis";
$GLOBALS['TL_LANG']['XPL']['modul_id']['0']['0'] = "Toon in module";
$GLOBALS['TL_LANG']['XPL']['modul_id']['0']['1'] = "Kies hier de box-module, waarin de huidige box getoond moet worden. Een box-module moet eerst gemaakt zijn in het backend gedeelte Modules. Als Module type kiest u daar Boxen. De plek op de pagina (links, rechts, midden, etc.) kiest u daar ook.<br>\nVervolgens moet u de nieuwe box-module onder Pagina layout koppelen met de desbetreffende kolommen (links, rechts, midden, etc.). Kies hier dezelfde kolom als bij het definiëren van de module. Meer informatie in de handleiding.";
 
?>
