<?php
/**
 * TL_ROOT/system/modules/boxes/languages/ru/modules.php 
 * 
 * Contao extension: boxes 1.13.2 stable 
 * Russian translation file 
 * 
 * Copyright : &copy; 2007 Christian Wenzel / &copy; 2008 computino.de Webservice 
 * License   : GPL v2 
 * Author    : Markus Milkereit (markus.milkereit), http://www.computino.de 
 * Translator: Dmitri Kuznetsov (kuzmich), http://www.onfreedom.ru 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['contentbox']['0'] = "Контент-блок";
$GLOBALS['TL_LANG']['MOD']['contentbox']['1'] = "Создание и управление странице-зависимым контентом.";
$GLOBALS['TL_LANG']['FMD']['contentbox']['0'] = "Контент-блок";
$GLOBALS['TL_LANG']['FMD']['contentbox']['1'] = "Создание и управление странице-зависимым контентом.";
 
?>
