<?php
/**
 * TL_ROOT/system/modules/boxes/languages/nl/modules.php 
 * 
 * TYPOlight extension: boxes 1.10.2 stable 
 * Dutch translation file 
 * 
 * Copyright : &copy; 2007 Christian Wenzel / &copy; 2008 computino.de Webservice 
 * License   : GPL v2 
 * Author    : Markus Milkereit (markus.milkereit), http://www.computino.de 
 * Translator: Just Schimmelpenninck (justs) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['contentbox']['0'] = "Boxen";
$GLOBALS['TL_LANG']['MOD']['contentbox']['1'] = "Toon inhoud op meerdere pagina's en beheer het vanuit één plek.";
$GLOBALS['TL_LANG']['FMD']['contentbox']['0'] = "Boxen";
$GLOBALS['TL_LANG']['FMD']['contentbox']['1'] = "Toon inhoud op meerdere pagina's en beheer het vanuit één plek.";

 
?>
