<?php
/**
 * TL_ROOT/system/modules/boxes/languages/fr/modules.php 
 * 
 * TYPOlight extension: boxes 1.10.4 stable 
 * French translation file 
 * 
 * Copyright : &copy; 2007 Christian Wenzel / &copy; 2008 computino.de Webservice 
 * License   : GPL v2 
 * Author    : Markus Milkereit (markus.milkereit), http://www.computino.de 
 * Translator: Jérôme DENIS (irongomme), http://www.sweb-developpement.com 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['contentbox']['0'] = "Boite à contenu";
$GLOBALS['TL_LANG']['MOD']['contentbox']['1'] = "Gérer et afficher les pages liés au contenu";
$GLOBALS['TL_LANG']['FMD']['contentbox']['0'] = "Boite à cotnenu";
$GLOBALS['TL_LANG']['FMD']['contentbox']['1'] = "Gérer et afficher les pages liés au contenu";

 
?>
