<?php
/**
 * TL_ROOT/system/modules/boxes/languages/fr/tl_boxen.php 
 * 
 * TYPOlight extension: boxes 1.10.4 stable 
 * French translation file 
 * 
 * Copyright : &copy; 2007 Christian Wenzel / &copy; 2008 computino.de Webservice 
 * License   : GPL v2 
 * Author    : Markus Milkereit (markus.milkereit), http://www.computino.de 
 * Translator: Jérôme DENIS (irongomme), http://www.sweb-developpement.com 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_boxen']['title']['0'] = "Titre";
$GLOBALS['TL_LANG']['tl_boxen']['title']['1'] = "Titre";
$GLOBALS['TL_LANG']['tl_boxen']['headline']['0'] = "Entête";
$GLOBALS['TL_LANG']['tl_boxen']['headline']['1'] = "Si vous saisissez une entête, celle-ci sera affiché en haut de l'élément de contenu";
$GLOBALS['TL_LANG']['tl_boxen']['content']['0'] = "Contenu";
$GLOBALS['TL_LANG']['tl_boxen']['cssID']['0'] = "ID / Classe(s) CSS";
$GLOBALS['TL_LANG']['tl_boxen']['cssID']['1'] = "Saisir un ID de feuille de style et/ou une ou plusieurs classe(s) CSS";
$GLOBALS['TL_LANG']['tl_boxen']['pages']['0'] = "Pages";
$GLOBALS['TL_LANG']['tl_boxen']['pages']['1'] = "Sélectionnez une ou plusieurs pages sur lesquelles la boite doit apparaître";
$GLOBALS['TL_LANG']['tl_boxen']['position']['0'] = "Position/Ordre";
$GLOBALS['TL_LANG']['tl_boxen']['position']['1'] = "Entrez un nombre (ex: 1 ou 2 etc) pour definir l'ordre des boites.";
$GLOBALS['TL_LANG']['tl_boxen']['modul_id']['0'] = "Connecter au module";
$GLOBALS['TL_LANG']['tl_boxen']['modul_id']['1'] = "Choisissez le module boite dans lequel la boite doit apparaître. Veuillez vous référer au Wiki pour plus de d'informations.";
$GLOBALS['TL_LANG']['tl_boxen']['space']['0'] = "Espace avant et après";
$GLOBALS['TL_LANG']['tl_boxen']['space']['1'] = "Veuillez saisir la taille de l'espace avant et après l'article en pixels.";
$GLOBALS['TL_LANG']['tl_boxen']['addImage']['0'] = "Ajouter une image";
$GLOBALS['TL_LANG']['tl_boxen']['addImage']['1'] = "Si vous choisissez cette option, une image sera ajouté aux nouveaux articles.";
$GLOBALS['TL_LANG']['tl_boxen']['imageUrl']['0'] = "Utiliser un lien sur l'image";
$GLOBALS['TL_LANG']['tl_boxen']['imageUrl']['1'] = "Veuillez saisir l'URL complète incluant le protocole réseau (ex: <em>http://www.domaine.com</em>) pour utiliser le lien sur l'image. Notez que dans ce cas, il ne sera pas possible d'avoir un lien pour agrandir l'image.";
$GLOBALS['TL_LANG']['tl_boxen']['title_legend'] = "Titre et entête";
$GLOBALS['TL_LANG']['tl_boxen']['text_legend'] = "Texte de contenu";
$GLOBALS['TL_LANG']['tl_boxen']['image_legend'] = "Propriétés de l'image";
$GLOBALS['TL_LANG']['tl_boxen']['column_legend'] = "Paramètres du module";
$GLOBALS['TL_LANG']['tl_boxen']['protected_legend'] = "Restrictions";
$GLOBALS['TL_LANG']['tl_boxen']['pages_legend'] = "Afficher sur les pages";
$GLOBALS['TL_LANG']['tl_boxen']['expert_legend'] = "Paramètres avancées";
$GLOBALS['TL_LANG']['tl_boxen']['new']['0'] = "Créer nouvelle boite";
$GLOBALS['TL_LANG']['tl_boxen']['edit']['0'] = "Editer";
$GLOBALS['TL_LANG']['tl_boxen']['copy']['0'] = "Copier";
$GLOBALS['TL_LANG']['tl_boxen']['delete']['0'] = "Effacer";
 
?>
