<?php
/**
 * TL_ROOT/system/modules/boxes/languages/ru/tl_boxen.php 
 * 
 * Contao extension: boxes 1.13.2 stable 
 * Russian translation file 
 * 
 * Copyright : &copy; 2007 Christian Wenzel / &copy; 2008 computino.de Webservice 
 * License   : GPL v2 
 * Author    : Markus Milkereit (markus.milkereit), http://www.computino.de 
 * Translator: Dmitri Kuznetsov (kuzmich), http://www.onfreedom.ru 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_boxen']['title']['0'] = "Название";
$GLOBALS['TL_LANG']['tl_boxen']['title']['1'] = "Название блока";
$GLOBALS['TL_LANG']['tl_boxen']['headline']['0'] = "Заголовок";
$GLOBALS['TL_LANG']['tl_boxen']['headline']['1'] = "Если вы ввели заголовок, он будет показан сверху элемента контента.";
$GLOBALS['TL_LANG']['tl_boxen']['content']['0'] = "Текст";
$GLOBALS['TL_LANG']['tl_boxen']['cssID']['0'] = "CSS ID и класс";
$GLOBALS['TL_LANG']['tl_boxen']['cssID']['1'] = "Если нужно создать специальный CSS-формат для определенного модуля, введите ID здесь. Этот ID будет использован в атрибутах ID модуля, и, таким образом, можно будет ссылаться на конкретный стиль.";
$GLOBALS['TL_LANG']['tl_boxen']['pages']['0'] = "Страницы";
$GLOBALS['TL_LANG']['tl_boxen']['pages']['1'] = "Выберите одну или несколько страниц, на которых должен появиться блок.";
$GLOBALS['TL_LANG']['tl_boxen']['reversePages']['0'] = "Отменить выбор страниц";
$GLOBALS['TL_LANG']['tl_boxen']['reversePages']['1'] = "С этой опцией, блок не отображаются на отдельных страницах. Если не выбрано, блок отображается везде.";
$GLOBALS['TL_LANG']['tl_boxen']['inheritPages']['0'] = "Выбор подстраниц";
$GLOBALS['TL_LANG']['tl_boxen']['inheritPages']['1'] = "Блок будет показан на всех подстраницах.";
$GLOBALS['TL_LANG']['tl_boxen']['position']['0'] = "Позиция/порядок";
$GLOBALS['TL_LANG']['tl_boxen']['position']['1'] = "Введите число (прим. 1 или 2 и т.д), чтобы определить порядок блоков.";
$GLOBALS['TL_LANG']['tl_boxen']['modul_id']['0'] = "Связь с модулем";
$GLOBALS['TL_LANG']['tl_boxen']['modul_id']['1'] = "Пожалуйста, выберите предварительно созданный модуль, в котором должен появиться блок. Для получения дополнительной информации читайте Wiki.";
$GLOBALS['TL_LANG']['tl_boxen']['space']['0'] = "Расстояние до и после";
$GLOBALS['TL_LANG']['tl_boxen']['space']['1'] = "Пожалуйcта, введите расстояние до и после элемента контента в пикселах.";
$GLOBALS['TL_LANG']['tl_boxen']['addImage']['0'] = "Добавить изображение";
$GLOBALS['TL_LANG']['tl_boxen']['addImage']['1'] = "Если вы выберете эту опцию, будет добавлен элемент типа \"изображение\".";
$GLOBALS['TL_LANG']['tl_boxen']['imageUrl']['0'] = "Использовать изображение как ссылку";
$GLOBALS['TL_LANG']['tl_boxen']['imageUrl']['1'] = "Пожалуйcта, введите полный URL ссылки, включая протокол (<em>http://www.domain.com</em>), для использования изображения в качестве ссылки. Обратите внимание, что в этом случае будет невозможно показать изображение в полный размер.";
$GLOBALS['TL_LANG']['tl_boxen']['published']['0'] = "Опубликовать блок";
$GLOBALS['TL_LANG']['tl_boxen']['published']['1'] = "Сделать блок видимым на веб-сайте";
$GLOBALS['TL_LANG']['tl_boxen']['start']['0'] = "Публиковать с";
$GLOBALS['TL_LANG']['tl_boxen']['start']['1'] = "Не отображать блок на веб-сайте до этого дня.";
$GLOBALS['TL_LANG']['tl_boxen']['stop']['0'] = "Публиковать до";
$GLOBALS['TL_LANG']['tl_boxen']['stop']['1'] = "Не отображать блок на веб-сайте после этого дня.";
$GLOBALS['TL_LANG']['tl_boxen']['title_legend'] = "Название и заголовок";
$GLOBALS['TL_LANG']['tl_boxen']['text_legend'] = "Содержание";
$GLOBALS['TL_LANG']['tl_boxen']['image_legend'] = "Настройки изображения";
$GLOBALS['TL_LANG']['tl_boxen']['column_legend'] = "Настройки модуля";
$GLOBALS['TL_LANG']['tl_boxen']['protected_legend'] = "Настройки доступа";
$GLOBALS['TL_LANG']['tl_boxen']['pages_legend'] = "Страницезависимый вывод";
$GLOBALS['TL_LANG']['tl_boxen']['expert_legend'] = "Экспертные настройки";
$GLOBALS['TL_LANG']['tl_boxen']['new']['0'] = "Создать новый блок";
$GLOBALS['TL_LANG']['tl_boxen']['edit']['0'] = "Редактировать блок";
$GLOBALS['TL_LANG']['tl_boxen']['copy']['0'] = "Копировать блок";
$GLOBALS['TL_LANG']['tl_boxen']['delete']['0'] = "Удалить блок";
$GLOBALS['TL_LANG']['XPL']['modul_id']['0']['0'] = "Описание";
$GLOBALS['TL_LANG']['XPL']['modul_id']['0']['1'] = "Здесь необходимо выбрать предварительно созданный модуль, в котором должен быть показан текущий блок. Для этого создайте новый модуль, укажите его имя, выберите тип модуля - \"контент-блок\" и определите позиции отображения (header, left, main, right, footer). Затем вы должны связать вновь созданный блок-модуль в макете страницы с определенной областью страницы (header, left, main, right, footer). Здесь необходимо выбрать туже область страницы, которая была определена раньше для блока. Для более подробной информации о элементе, посетите Wiki раздел по этому модулю.";
 
?>
